source 'https://rubygems.org'

gem 'puppet',                                                    '~> 8.4'
gem 'onceover',                                                  '~> 3.22'
gem 'ffi',                                                       '~> 1.12', '>= 1.12.2'
gem 'hiera-eyaml',                                               '~> 3.2', '>= 3.2.1'
gem 'json',                                                      '~> 2.3'
gem 'nokogiri',                                                  '~> 1.10', '>= 1.10.9'
gem 'onceover-codequality',                                      '~> 0.8', '>= 0.8.0'
gem 'onceover-octocatalog-diff',                                 '~> 0.1', '>= 0.1.8'
gem 'onceover-lookup',                                           '~> 0.1', '>= 0.1.1'
gem 'parallel',                                                  '~> 1.20', '>= 1.20.1'               
gem 'puppet-lint-classes_and_types_beginning_with_digits-check', '~> 1.0'
gem 'puppet-lint-leading_zero-check',                            '~> 1.0'
gem 'puppet-lint-legacy_facts-check',                            '~> 1.0', '>= 1.0.4'
gem 'puppet-lint-top_scope_facts-check',                         '~> 1.0'
gem 'puppet-lint-trailing_comma-check',                          '~> 0.4.1'
gem 'puppet-lint-unquoted_string-check',                         '~> 2.0'
gem 'puppet-lint-variable_contains_upcase',                      '~> 1.2'
gem 'puppet-lint-version_comparison-check',                      '~> 1.0'
gem 'puppet-lint',                                               '~> 2.4'
gem 'puppet-strings',                                            '~> 2.6'
gem 'puppet-syntax',                                             '~> 3.2.0'
gem 'puppetlabs_spec_helper',                                    '~> 5.0'
gem 'r10k',                                                      '~> 3.8'
gem 'ra10ke',                                                    '~> 1.0'
gem 'rspec-puppet',                                              '~> 2.12.0'
gem 'rubocop',                                                   '~> 1.12'
gem 'unf_ext',                                                   '~> 0.0.8'
gem 'yamllint',                                                  '~> 0.0.9'
