source 'https://rubygems.org'

gem 'puppet',                                                    '~> 8.10'
gem 'onceover',                                                  '~> 3.22'
gem 'ffi',                                                       '~> 1.17'
gem 'hiera-eyaml',                                               '~> 4.3'
gem 'json',                                                      '~> 2.12'
gem 'nokogiri',                                                  '~> 1.18'
gem 'onceover-codequality',                                      '~> 0.13'
gem 'onceover-octocatalog-diff',                                 '~> 0.1', '>= 0.1.8'
gem 'onceover-lookup',                                           '~> 0.1', '>= 0.1.1'
gem 'parallel',                                                  '~> 1.20', '>= 1.20.1'
gem 'puppet-lint-leading_zero-check',                            '~> 2.0'
gem 'puppet-lint-trailing_comma-check',                          '~> 2.0'
gem 'puppet-lint-unquoted_string-check',                         '~> 3.0'
gem 'puppet-lint-variable_contains_upcase',                      '~> 2.0'
gem 'puppet-lint-version_comparison-check',                      '~> 2.0'
gem 'puppet-lint',                                               '~> 4.0'
gem 'puppet-strings',                                            '~> 4.0'
gem 'puppet-syntax',                                             '~> 4.0'
gem 'puppetlabs_spec_helper',                                    '~> 8.0'
gem 'r10k',                                                      '~> 5.0'
gem 'ra10ke',                                                    '~> 4.0'
gem 'rspec-puppet',                                              '~> 5.0'
gem 'rubocop',                                                   '~> 1.75'
gem 'unf_ext',                                                   '~> 0.0.9'
gem 'yamllint',                                                  '~> 0.0.9'
gem 'rexml'
gem 'bigdecimal',                                                '= 3.2.1'
